@extends('layouts.master_layout.master_layout')
@section('title','Bill Details')
@section('content')

<?php
$adjustment_amount = $billrecord->billed_amount - $billrecord->amount_paid
?>
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Company Invoice details</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active">Company Invoice Details</li>
        </ol>
        </div>
     </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Bill Transaction Detail</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      {{-- {{ dd("hi") }} --}}
      <div class="card-body">
        <div class="row">
          <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
            <div class="row">
              <div class="col-12 col-sm-4">
                <div class="info-box bg-light">
                  <div class="info-box-content">
                    <span class="info-box-text text-center text-muted">Billed Amount</span>
                    <span class="info-box-number text-center text-muted mb-0">Rs. {{ number_format($billrecord->billed_amount) }}</span>
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-4">
                <div class="info-box bg-light">
                  <div class="info-box-content">
                    <span class="info-box-text text-center text-muted">Paid Amount</span>
                    <span class="info-box-number text-center text-muted mb-0 text-green">Rs. {{ number_format($billrecord->amount_paid) }}</span>
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-4">
                <div class="info-box bg-light">
                  <div class="info-box-content">
                    <span class="info-box-text text-center text-muted">Adjusted Amount</span>
                    <span class="info-box-number text-center text-muted mb-0 text-red">Rs. {{ number_format($adjustment_amount) }}</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <h4>Invoice Details - Description & Remarks</h4>
                  <div class="post">
              <br>
                    <!-- /.user-block -->
                    <h5>Details</h5>
                    <p>
                      {{ $billrecord->description }}
                    </p>
                    <hr>
                    <h5>Remarks</h5>
                    <p>{{ $billrecord->remarks }}</p>
                    <p>
                      <a href="#" class="link-black text-sm"><i class="fas fa-link mr-1"></i> Demo File 1 v2</a>
                    </p>
                  </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
            <h3 class="text-primary"><i class="fas fa-building"></i> {{ $billrecord->brand->name }} | {{ $billrecord->category->name }}</h3>
            <p class="text-muted">{{ $billrecord->brand->description }}</p>
            <br>
            <b class="d-block">Information</b>
            <div class="text-muted">
              <p class="text-sm">Company Invoice Category
                <b class="d-block">{{ $billrecord->category->name }}</b>
              </p>
              <p class="text-sm">Company Invoice Generated by:
                <b class="d-block">{{ $billrecord->generated_user }}</b>
              </p>
              <p class="text-sm">Company Invoice created on:
                <b class="d-block"> {{ \Carbon\Carbon::parse($billrecord->created_at)->format('d-m-Y') }}</b>
              </p>
             

            </div>

            {{-- <h5 class="mt-5 text-muted">Project files</h5>
            <ul class="list-unstyled">
              <li>
                <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-file-word"></i> Functional-requirements.docx</a>
              </li>
              <li>
                <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-file-pdf"></i> UAT.pdf</a>
              </li>
              <li>
                <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-envelope"></i> Email-from-flatbal.mln</a>
              </li>
              <li>
                <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-image "></i> Logo.png</a>
              </li>
              <li>
                <a href="" class="btn-link text-secondary"><i class="far fa-fw fa-file-word"></i> Contract-10_12_2014.docx</a>
              </li>
            </ul> --}}
            <div class="row">
{{-- {{ route('ledger-record-delete', ['account' => $billrecord->id]) }} --}}
              <div class="text-left mt-5 mb-3">
                <a href="#" 
                  class="btn btn-sm btn-danger delete-bill" onclick="confirmDelete({{ $billrecord->id }})"
                data-url=""
                ><i class="fas fa-trash"></i>  Delete Bill</a>
              </div>

            
              
              <div class="text-left mt-5 mb-3" style="margin-left:15px;">
                <a href="{{ route('view-finances')}}" class="btn btn-sm btn-warning">Return Back</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->

  </section>


  {{-- @push('scripts')
  <script>
      // Toaster
      @if (Session::has('success'))
      toastr.options = {
              "closeButton": true,
              "progressBar": true
          }
          toastr.success("{{ session('success') }}");
      @endif
      @if (Session::has('error'))
      toastr.options = {
              "closeButton": true,
              "progressBar": true
          }
          toastr.error("{{ session('error') }}");
      @endif
  </script>
  @endpush --}}
  <script>
    function confirmDelete(itemId) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                // Construct the URL for the delete route
                var deleteUrl = '{{ route("ledger-record-delete", ":id") }}';
                deleteUrl = deleteUrl.replace(':id', itemId);

                // Send AJAX request to delete the item
                $.ajax({
                    url: deleteUrl,
                    type: 'DELETE',
                    data: {
                        _token: '{{ csrf_token() }}'
                    },
                    success: function(response) {
                        Swal.fire(
                            'Deleted!',
                            'Your item has been deleted.',
                            'success'
                        ).then(() => {
                            // Redirect to the desired page
                            window.location.href = '{{ route("view-finances") }}'; // Replace with your desired route
                        });
                    },
                    error: function(xhr) {
                        Swal.fire(
                            'Error!',
                            'An error occurred while deleting the item.',
                            'error'
                        );
                    }
                });
            }
        });
    }
</script>
@endsection